version: '3.8'

services:
  app:
    container_name: cats-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SYNCHRONIZE_DB=${SYNCHRONIZE_DB}
    command: bash -c "npm install && npm run start:dev"
    depends_on:
      - db

  db:
    container_name: cats-db
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - cats-postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: cats-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - cats-pgadmin-data:/var/lib/pgadmin

volumes:
  cats-postgres-data:
  cats-pgadmin-data:
